package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.15
 * 2014-09-09T14:58:40.584+01:00
 * Generated source version: 2.6.15
 * 
 */
@WebService(targetNamespace = "http://service.com/", name = "IHelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.com/", className = "com.service.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.com/", className = "com.service.GetUserResponse")
    public com.service.User getUser();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.com/", className = "com.service.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.com/", className = "com.service.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://service.com/", className = "com.service.SayHiToUser")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://service.com/", className = "com.service.SayHiToUserResponse")
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.service.User arg0
    );
}
