CREATE DATABASE  IF NOT EXISTS `nahibernate`;

USE `nahibernate`;DROP TABLE IF EXISTS `personne`;

DROP TABLE IF EXISTS `entreprise`;

CREATE TABLE `entreprise` (
  `ENTREPRISE_ID` int(11) NOT NULL,
  `NOM` varchar(45) DEFAULT NULL,
  `ACTIVITE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ENTREPRISE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `personne` (
  `PERSONNE_ID` int(11) NOT NULL,
  `ENTREPRISE_ID` int(11) DEFAULT NULL,
  `NOM` varchar(45) DEFAULT NULL,
  `PRENOM` varchar(45) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  PRIMARY KEY (`PERSONNE_ID`),
  KEY `fk_entreprise_personne` (`ENTREPRISE_ID`),
  CONSTRAINT `fk_entreprise_personne` FOREIGN KEY (`ENTREPRISE_ID`) REFERENCES `entreprise` (`ENTREPRISE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


